repositories:
- name: traefik
  url: https://traefik.github.io/charts
- name: cnpg
  url: https://cloudnative-pg.github.io/charts
- name: longhorn
  url: https://charts.longhorn.io
- name: metrics-server
  url: https://kubernetes-sigs.github.io/metrics-server/
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: cilium
  url: https://helm.cilium.io/
- name: jetstack
  url: https://charts.jetstack.io
- name: mittwald
  url: https://helm.mittwald.de


releases:
- name: cilium
  chart: cilium/cilium
  namespace: kube-system
  version: 1.16.2
  values:
  - ./cilium-values.yaml
- name: cert-manager
  chart: jetstack/cert-manager
  namespace: cert-manager
  createNamespace: true
  version: 1.15.3
  set:
  - name: crds.enabled
    value: true
- name: kubernetes-replicator
  chart: mittwald/kubernetes-replicator
  namespace: kube-system
  version: 2.10.2
- name: traefik
  chart: traefik/traefik
  createNamespace: true
  namespace: traefik
  values:
  - ./traefik-values.yaml
- name: longhorn
  chart: longhorn/longhorn
  namespace: longhorn-system
  version: 1.7.1
- name: cnpg
  chart: cnpg/cloudnative-pg
  createNamespace: true
  namespace: cnpg-system
- name: metrics-server
  chart: metrics-server/metrics-server
  namespace: kube-system
  version: 3.12.1
  set:
  - name: args[0]
    value: --kubelet-insecure-tls
- name: kube-prometheus-stack
  chart: prometheus-community/kube-prometheus-stack
  namespace: monitoring
  createNamespace: true
  version: 62.7.0
  values:
  - ./prom-values.yaml
  secrets:
  - ./prom-secrets.yaml
  set:
  - name: installCRDs
    value: true
