repositories:
- name: traefik
  url: https://traefik.github.io/charts
- name: cnpg
  url: https://cloudnative-pg.github.io/charts
- name: longhorn
  url: https://charts.longhorn.io

releases:
- name: traefik
  chart: traefik/traefik
  createNamespace: true
  namespace: traefik
  values:
  - ./traefik-values.yaml
- name: cnpg
  chart: cnpg/cloudnative-pg
  createNamespace: true
  namespace: cnpg-system
- name: longhorn
  chart: longhorn/longhorn
  createNamespace: true
  namespace: longhorn-system
  version: 1.7.1
