repositories:
- name: traefik
  url: https://traefik.github.io/charts
- name: cnpg
  url: https://cloudnative-pg.github.io/charts
- name: longhorn
  url: https://charts.longhorn.io
- name: metrics-server
  url: https://kubernetes-sigs.github.io/metrics-server/
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts


releases:
- name: traefik
  chart: traefik/traefik
  createNamespace: true
  namespace: traefik
  values:
  - ./traefik-values.yaml
- name: cnpg
  chart: cnpg/cloudnative-pg
  createNamespace: true
  namespace: cnpg-system
- name: longhorn
  chart: longhorn/longhorn
  namespace: longhorn-system
  version: 1.7.1
- name: metrics-server
  chart: metrics-server/metrics-server
  namespace: kube-system
  version: 3.12.1
- name: kube-prometheus-stack
  chart: prometheus-community/kube-prometheus-stack
  namespace: monitoring
  createNamespace: true
  version: 62.7.0
  values:
  - ./prom-values.yaml
  set:
    - name: installCRDs
      value: true
