apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

# secretGenerator:
# - name: cloudflare-api-token-secret
#   envs:
#   - .env.secret

resources:
- certIssuer.yaml
- cert.yaml
