repositories:
- name: traefik
  url: https://traefik.github.io/charts
- name: metallb
  url: https://metallb.github.io/metallb

releases:
- name: traefik
  chart: traefik/traefik
  createNamespace: true
  namespace: traefik
  set:
  - name: providers.kubernetesGateway.enable
    value: true
- name: metallb
  chart: metallb/metallb
  createNamespace: true
  namespace: metallb-system
